# Generated by Django 5.2.17 on 2026-08-29 15:40

import stats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0036_pt_br'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='extra_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='mission',
            name='score_dict',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='object',
            name='cls',
            field=models.CharField(blank=True, choices=[('aaa_heavy', 'aaa_heavy'), ('aaa_light', 'aaa_light'), ('aaa_mg', 'aaa_mg'), ('aerostat', 'aerostat'), ('aircraft_gunner', 'aircraft_gunner'), ('aircraft_heavy', 'aircraft_heavy'), ('aircraft_light', 'aircraft_light'), ('aircraft_medium', 'aircraft_medium'), ('aircraft_pilot', 'aircraft_pilot'), ('aircraft_static', 'aircraft_static'), ('aircraft_transport', 'aircraft_transport'), ('aircraft_turret', 'aircraft_turret'), ('armoured_vehicle', 'armoured_vehicle'), ('artillery_field', 'artillery_field'), ('artillery_howitzer', 'artillery_howitzer'), ('artillery_rocket', 'artillery_rocket'), ('block', 'block'), ('bomb', 'bomb'), ('building_big', 'building_big'), ('building_medium', 'building_medium'), ('building_small', 'building_small'), ('bullet', 'bullet'), ('car', 'car'), ('cruise_missile', 'cruise_missile'), ('driver', 'driver'), ('explosion', 'explosion'), ('locomotive', 'locomotive'), ('machine_gunner', 'machine_gunner'), ('parachute', 'parachute'), ('rocket', 'rocket'), ('searchlight', 'searchlight'), ('ship', 'ship'), ('ship_heavy', 'ship_heavy'), ('ship_light', 'ship_light'), ('ship_medium', 'ship_medium'), ('shell', 'shell'), ('tank_heavy', 'tank_heavy'), ('tank_light', 'tank_light'), ('tank_medium', 'tank_medium'), ('tank_driver', 'tank_driver'), ('tank_turret', 'tank_turret'), ('trash', 'trash'), ('truck', 'truck'), ('vehicle_crew', 'vehicle_crew'), ('vehicle_static', 'vehicle_static'), ('vehicle_turret', 'vehicle_turret'), ('wagon', 'wagon')], max_length=24),
        ),
        migrations.AlterField(
            model_name='player',
            name='ammo',
            field=models.JSONField(default=stats.models.default_ammo),
        ),
        migrations.AlterField(
            model_name='player',
            name='killboard_pve',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='player',
            name='killboard_pvp',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='player',
            name='sorties_cls',
            field=models.JSONField(default=stats.models.default_sorties_cls),
        ),
        migrations.AlterField(
            model_name='playeraircraft',
            name='ammo',
            field=models.JSONField(default=stats.models.default_ammo),
        ),
        migrations.AlterField(
            model_name='playeraircraft',
            name='killboard_pve',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='playeraircraft',
            name='killboard_pvp',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='playermission',
            name='ammo',
            field=models.JSONField(default=stats.models.default_ammo),
        ),
        migrations.AlterField(
            model_name='playermission',
            name='killboard_pve',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='playermission',
            name='killboard_pvp',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='ammo',
            field=models.JSONField(default=stats.models.default_ammo),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='bonus',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='debug',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='killboard_pve',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='killboard_pvp',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='score_dict',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='squad',
            name='sorties_cls',
            field=models.JSONField(default=stats.models.default_sorties_cls),
        ),
        migrations.AlterField(
            model_name='vlife',
            name='ammo',
            field=models.JSONField(default=stats.models.default_ammo),
        ),
        migrations.AlterField(
            model_name='vlife',
            name='killboard_pve',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vlife',
            name='killboard_pvp',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vlife',
            name='sorties_cls',
            field=models.JSONField(default=stats.models.default_sorties_cls),
        ),
    ]
