# Generated by Django 5.2.17 on 2026-08-29 15:40

import django.core.validators
import squads.models
import stuff.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0003_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='logo',
            field=models.ImageField(blank=True, storage=stuff.storage.OverwriteStorage(), upload_to=squads.models.squad_logo_path, validators=[django.core.validators.validate_image_file_extension], verbose_name='squad logo'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='tag',
            field=models.CharField(db_collation='und-x-icu', max_length=16, verbose_name='squad tag'),
        ),
    ]
